# Generated by Django 5.1.1 on 2024-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.IntegerField()),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('irctc_order_no', models.BigIntegerField(blank=True, null=True)),
                ('bank_booking_ref_no', models.BigIntegerField(blank=True, null=True)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credited_date', models.DateField(blank=True, null=True)),
                ('cus_account_no', models.CharField(blank=True, max_length=25, null=True)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('txn_date', 'bank_code', 'credited_date', 'irctc_order_no', 'bank_booking_ref_no'), name='unique_bookingdata_constraint')],
            },
        ),
        migrations.CreateModel(
            name='RefundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.IntegerField()),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('irctc_order_no', models.BigIntegerField(blank=True, null=True)),
                ('bank_booking_ref_no', models.BigIntegerField(blank=True, null=True)),
                ('bank_refund_ref_no', models.BigIntegerField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debited_date', models.DateField(blank=True, null=True)),
                ('cus_account_no', models.CharField(blank=True, max_length=25, null=True)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('refund_date', 'bank_code', 'debited_date', 'irctc_order_no', 'bank_booking_ref_no', 'bank_refund_ref_no'), name='unique_refunddata_constraint')],
            },
        ),
    ]
